export const CREATE_EVENT_PENDING = "CREATE_EVENT_PENDING";
export const CREATE_EVENT_FULFILLED = "CREATE_EVENT_FULFILLED";
export const CREATE_EVENT_REJECTED = "CREATE_EVENT_REJECTED";

export const CREATE_DRAFT_PENDING = "CREATE_DRAFT_PENDING";
export const CREATE_DRAFT_FULFILLED = "CREATE_DRAFT_FULFILLED";
export const CREATE_DRAFT_REJECTED = "CREATE_DRAFT_REJECTED";

export const PREPARE_UPDATE_EVENT_PENDING = "PREPARE_UPDATE_EVENT_PENDING";
export const PREPARE_UPDATE_EVENT_FULFILLED = "PREPARE_UPDATE_EVENT_FULFILLED";
export const PREPARE_UPDATE_EVENT_REJECTED = "PREPARE_UPDATE_EVENT_REJECTED";

export const DELETE_DRAFT_PENDING = "DELETE_DRAFT_PENDING";
export const DELETE_DRAFT_FULFILLED = "DELETE_DRAFT_FULFILLED";
export const DELETE_DRAFT_REJECTED = "DELETE_DRAFT_REJECTED";

export const FETCH_ITEMS_QUANTITY = "FETCH_ITEMS_QUANTITY";
export const FETCH_ITEMS_QUANTITY_PENDING = "FETCH_ITEMS_QUANTITY_PENDING";
export const FETCH_ITEMS_QUANTITY_FULFILLED = "FETCH_ITEMS_QUANTITY_FULFILLED";
export const FETCH_ITEMS_QUANTITY_REJECTED = "FETCH_ITEMS_QUANTITY_REJECTED";

export const FETCH_DRAFT = "FETCH_DRAFT";
export const FETCH_DRAFT_PENDING = "FETCH_DRAFT_PENDING";
export const FETCH_DRAFT_FULFILLED = "FETCH_DRAFT_FULFILLED";
export const FETCH_DRAFT_REJECTED = "FETCH_DRAFT_REJECTED";

export const FETCH_ITEMS = "FETCH_ITEMS";
export const FETCH_ITEMS_PENDING = "FETCH_ITEMS_PENDING";
export const FETCH_ITEMS_FULFILLED = "FETCH_ITEMS_FULFILLED";
export const FETCH_ITEMS_REJECTED = "FETCH_ITEMS_REJECTED";

export const CREATE_ITEMS_PENDING = "CREATE_ITEMS_PENDING";
export const CREATE_ITEMS_FULFILLED = "CREATE_ITEMS_FULFILLED";
export const CREATE_ITEMS_REJECTED = "CREATE_ITEMS_REJECTED";

export const DELETE_ITEMS_PENDING = "DELETE_ITEMS_PENDING";
export const DELETE_ITEMS_FULFILLED = "DELETE_ITEMS_FULFILLED";
export const DELETE_ITEMS_REJECTED = "DELETE_ITEMS_REJECTED";

export const FETCH_CATEGORIES = "FETCH_CATEGORIES";
export const FETCH_CATEGORIES_PENDING = "FETCH_CATEGORIES_PENDING";
export const FETCH_CATEGORIES_FULFILLED = "FETCH_CATEGORIES_FULFILLED";
export const FETCH_CATEGORIES_REJECTED = "FETCH_CATEGORIES_REJECTED";

export const CREATE_CATEGORIES_PENDING = "CREATE_CATEGORIES_PENDING";
export const CREATE_CATEGORIES_FULFILLED = "CREATE_CATEGORIES_FULFILLED";
export const CREATE_CATEGORIES_REJECTED = "CREATE_CATEGORIES_REJECTED";

export const DELETE_CATEGORIES_PENDING = "DELETE_CATEGORIES_PENDING";
export const DELETE_CATEGORIES_FULFILLED = "DELETE_CATEGORIES_FULFILLED";
export const DELETE_CATEGORIES_REJECTED = "DELETE_CATEGORIES_REJECTED";

export const FETCH_ORDER_PENDING = "FETCH_ORDER_PENDING";
export const FETCH_ORDER_FULFILLED = "FETCH_ORDER_FULFILLED";
export const FETCH_ORDER_REJECTED = "FETCH_ORDER_REJECTED";

export const UPDATE_ORDER_PENDING = "UPDATE_ORDER_PENDING";
export const UPDATE_ORDER_FULFILLED = "UPDATE_ORDER_FULFILLED";
export const UPDATE_ORDER_REJECTED = "UPDATE_ORDER_REJECTED";

export const FETCH_TARGETS = "FETCH_TARGETS";
export const FETCH_TARGETS_PENDING = "FETCH_TARGETS_PENDING";
export const FETCH_TARGETS_FULFILLED = "FETCH_TARGETS_FULFILLED";
export const FETCH_TARGETS_REJECTED = "FETCH_TARGETS_REJECTED";

export const CREATE_TARGETS_PENDING = "CREATE_TARGETS_PENDING";
export const CREATE_TARGETS_FULFILLED = "CREATE_TARGETS_FULFILLED";
export const CREATE_TARGETS_REJECTED = "CREATE_TARGETS_REJECTED";

export const DELETE_TARGETS_PENDING = "DELETE_TARGETS_PENDING";
export const DELETE_TARGETS_FULFILLED = "DELETE_TARGETS_FULFILLED";
export const DELETE_TARGETS_REJECTED = "DELETE_TARGETS_REJECTED";

export const FETCH_UPCOMING_ORDER_PENDING = "FETCH_UPCOMING_ORDER_PENDING";
export const FETCH_UPCOMING_ORDER_FULFILLED = "FETCH_UPCOMING_ORDER_FULFILLED";
export const FETCH_UPCOMING_ORDER_REJECTED = "FETCH_UPCOMING_ORDER_REJECTED";

export const FETCH_HOME_ORDER_PENDING = "FETCH_HOME_ORDER_PENDING";
export const FETCH_HOME_ORDER_FULFILLED = "FETCH_HOME_ORDER_FULFILLED";
export const FETCH_HOME_ORDER_REJECTED = "FETCH_HOME_ORDER_REJECTED";

export const PRINT_ORDER_PENDING = "PRINT_ORDER_PENDING";
export const PRINT_ORDER_FULFILLED = "PRINT_ORDER_FULFILLED";
export const PRINT_ORDER_REJECTED = "PRINT_ORDER_REJECTED";

export const FETCH_CUSTOMER = "FETCH_CUSTOMER";
export const FETCH_CUSTOMER_PENDING = "FETCH_CUSTOMER_PENDING";
export const FETCH_CUSTOMER_FULFILLED = "FETCH_CUSTOMER_FULFILLED";
export const FETCH_CUSTOMER_REJECTED = "FETCH_CUSTOMER_REJECTED";
export const CREATE_CUSTOMER = "CREATE_CUSTOMER";

export const ITEM_EXPENSE_PENDING = "ITEM_EXPENSE_PENDING";
