"use strict";

module.exports = {
  up: (queryInterface, Sequelize) => {
    return queryInterface.bulkInsert(
      "items",
      [
        {
          id: 1,
          key: 1,
          sku: "C_P_T 005",
          quantity: 17,
          rate: 200,
          category_id: 14,
          name: "Carpet (6x9) N",
          createdAt: new Date(),
          updatedAt: new Date()
        },
        {
          id: 2,
          key: 2,
          sku: "A_24743",
          quantity: 20,
          rate: 300,
          category_id: 14,
          name: "Arrangement Charges",
          createdAt: new Date(),
          updatedAt: new Date()
        },
        {
          id: 3,
          key: 3,
          sku: "B-S 12A",
          quantity: 12,
          rate: 15,
          category_id: 14,
          name: "Bowl Spoon A",
          createdAt: new Date(),
          updatedAt: new Date()
        },
        {
          id: 4,
          key: 4,
          sku: "B-S36|B",
          quantity: 36,
          rate: 15,
          category_id: 14,
          name: "Bowl Spoon B",
          createdAt: new Date(),
          updatedAt: new Date()
        },
        {
          id: 5,
          key: 5,
          sku: "BL_2675",
          quantity: 7,
          rate: 35,
          category_id: 14,
          name: "Bowl",
          createdAt: new Date(),
          updatedAt: new Date()
        },
        {
          id: 6,
          key: 6,
          sku: "Bl_74556",
          quantity: 20,
          rate: 80,
          category_id: 14,
          name: "Bolster",
          createdAt: new Date(),
          updatedAt: new Date()
        },
        {
          id: 7,
          key: 7,
          sku: "BM-2685",
          quantity: 21,
          rate: 20,
          category_id: 14,
          name: "Bowl (M)",
          createdAt: new Date(),
          updatedAt: new Date()
        },
        {
          id: 8,
          key: 8,
          sku: "BS-77666",
          quantity: 17,
          rate: 10,
          category_id: 14,
          name: "Bowl Spoon M",
          createdAt: new Date(),
          updatedAt: new Date()
        },
        {
          id: 9,
          key: 9,
          sku: "B_C_L",
          quantity: 30,
          rate: 50,
          category_id: 14,
          name: "Bulb Colorful Light",
          createdAt: new Date(),
          updatedAt: new Date()
        },
        {
          id: 10,
          key: 10,
          sku: "C-C-J",
          quantity: 20,
          rate: 20,
          category_id: 4,
          name: "Chair Cover (J)",
          createdAt: new Date(),
          updatedAt: new Date()
        },
        {
          id: 11,
          key: 11,
          sku: "C-P",
          quantity: 100,
          rate: 10,
          category_id: 14,
          name: "Coffee Cup",
          createdAt: new Date(),
          updatedAt: new Date()
        },
        {
          id: 12,
          key: 12,
          sku: "Cch_10021",
          quantity: 100,
          rate: 120,
          category_id: 3,
          name: "Acrylic Chaivari Chair",
          createdAt: new Date(),
          updatedAt: new Date()
        },
        {
          id: 13,
          key: 13,
          sku: "Cc_1010",
          quantity: 150,
          rate: 40,
          category_id: 14,
          name: "Crockery",
          createdAt: new Date(),
          updatedAt: new Date()
        },
        {
          id: 14,
          key: 14,
          sku: "ChCr_26837",
          quantity: 100,
          rate: 10,
          category_id: 4,
          name: "Chair Cover",
          createdAt: new Date(),
          updatedAt: new Date()
        },
        {
          id: 15,
          key: 15,
          sku: "Ch_10001",
          quantity: 100,
          rate: 20,
          category_id: 3,
          name: "Chair",
          createdAt: new Date(),
          updatedAt: new Date()
        },
        {
          id: 16,
          key: 16,
          sku: "Ch_2686",
          quantity: 12,
          rate: 60,
          category_id: 14,
          name: "Chatai",
          createdAt: new Date(),
          updatedAt: new Date()
        },
        {
          id: 17,
          key: 17,
          sku: "Ci-242634",
          quantity: 80,
          rate: 100,
          category_id: 14,
          name: "Chandni",
          createdAt: new Date(),
          updatedAt: new Date()
        },
        {
          id: 18,
          key: 18,
          sku: "Cjd_242634",
          quantity: 40,
          rate: 200,
          category_id: 14,
          name: "Chandni jacquard (10x10)",
          createdAt: new Date(),
          updatedAt: new Date()
        },
        {
          id: 19,
          key: 19,
          sku: "CL_2665",
          quantity: 4,
          rate: 100,
          category_id: 14,
          name: "Cooler",
          createdAt: new Date(),
          updatedAt: new Date()
        },
        {
          id: 20,
          key: 20,
          sku: "CS-77666",
          quantity: 36,
          rate: 10,
          category_id: 14,
          name: "Bowl Spoon (S)",
          createdAt: new Date(),
          updatedAt: new Date()
        },
        {
          id: 21,
          key: 21,
          sku: "Cty",
          quantity: 100,
          rate: 80,
          category_id: 14,
          name: "Cutlery",
          createdAt: new Date(),
          updatedAt: new Date()
        },
        {
          id: 22,
          key: 22,
          sku: "C_Cvr_J",
          quantity: 206,
          rate: 20,
          category_id: 4,
          name: "Long Back Chair Cover (J)",
          createdAt: new Date(),
          updatedAt: new Date()
        },
        {
          id: 23,
          key: 23,
          sku: "C_C_T",
          quantity: 110,
          rate: 15,
          category_id: 4,
          name: "Chair cover Dabbi tapi",
          createdAt: new Date(),
          updatedAt: new Date()
        },
        {
          id: 24,
          key: 24,
          sku: "C_D",
          quantity: 500,
          rate: 26,
          category_id: 14,
          name: "cold drink",
          createdAt: new Date(),
          updatedAt: new Date()
        },
        {
          id: 25,
          key: 25,
          sku: "C_DP_10101",
          quantity: 4,
          rate: 150,
          category_id: 14,
          name: "Cooler D/P",
          createdAt: new Date(),
          updatedAt: new Date()
        },
        {
          id: 26,
          key: 26,
          sku: "C_H_ 0017",
          quantity: 1,
          rate: 250,
          category_id: 14,
          name: "Cooler (Hot n Cold)",
          createdAt: new Date(),
          updatedAt: new Date()
        },
        {
          id: 27,
          key: 27,
          sku: "C_L 042",
          quantity: 30,
          rate: 50,
          category_id: 14,
          name: "color Light",
          createdAt: new Date(),
          updatedAt: new Date()
        },
        {
          id: 28,
          key: 28,
          sku: "C_P",
          quantity: 8,
          rate: 150,
          category_id: 14,
          name: "Carpet (6x9)",
          createdAt: new Date(),
          updatedAt: new Date()
        },
        {
          id: 29,
          key: 29,
          sku: "C_P_T 003",
          quantity: 7,
          rate: 600,
          category_id: 14,
          name: "Carpet (30 x 12)",
          createdAt: new Date(),
          updatedAt: new Date()
        },
        {
          id: 30,
          key: 30,
          sku: "C_P_T 002",
          quantity: 20,
          rate: 300,
          category_id: 14,
          name: "carpet (15*6)",
          createdAt: new Date(),
          updatedAt: new Date()
        },
        {
          id: 31,
          key: 31,
          sku: "C_T 001",
          quantity: 4,
          rate: 200,
          category_id: 9,
          name: "centre table",
          createdAt: new Date(),
          updatedAt: new Date()
        },
        {
          id: 32,
          key: 32,
          sku: "D T I",
          quantity: 2,
          rate: 250,
          category_id: 14,
          name: "Drawing Pins + Tissues + Ispirt",
          createdAt: new Date(),
          updatedAt: new Date()
        },
        {
          id: 33,
          key: 33,
          sku: "D W S",
          quantity: 2,
          rate: 200,
          category_id: 8,
          name: "Dish Wash Service",
          createdAt: new Date(),
          updatedAt: new Date()
        },
        {
          id: 34,
          key: 34,
          sku: "D-L",
          quantity: 1,
          rate: 1200,
          category_id: 14,
          name: "Doli",
          createdAt: new Date(),
          updatedAt: new Date()
        },
        {
          id: 35,
          key: 35,
          sku: "D-P-7",
          quantity: 150,
          rate: 7,
          category_id: 7,
          name: "Dinner Plate (Melamine)",
          createdAt: new Date(),
          updatedAt: new Date()
        },
        {
          id: 36,
          key: 36,
          sku: "D-P-I",
          quantity: 10,
          rate: 150,
          category_id: 14,
          name: "Drawing Pins + Ispirt",
          createdAt: new Date(),
          updatedAt: new Date()
        },
        {
          id: 37,
          key: 37,
          sku: "D-S 12A",
          quantity: 12,
          rate: 15,
          category_id: 8,
          name: "Dish spoon A",
          createdAt: new Date(),
          updatedAt: new Date()
        },
        {
          id: 38,
          key: 38,
          sku: "D-S 12B",
          quantity: 12,
          rate: 15,
          category_id: 8,
          name: "Dish spoon B",
          createdAt: new Date(),
          updatedAt: new Date()
        },
        {
          id: 39,
          key: 39,
          sku: "D-T",
          quantity: 6,
          rate: 200,
          category_id: 9,
          name: "Dining Table 4x4",
          createdAt: new Date(),
          updatedAt: new Date()
        },
        {
          id: 40,
          key: 40,
          sku: "Df_101",
          quantity: 5,
          rate: 100,
          category_id: 14,
          name: "Daff",
          createdAt: new Date(),
          updatedAt: new Date()
        },
        {
          id: 41,
          key: 41,
          sku: "Dh-3474",
          quantity: 24,
          rate: 20,
          category_id: 8,
          name: "Dish",
          createdAt: new Date(),
          updatedAt: new Date()
        },
        {
          id: 42,
          key: 42,
          sku: "Dh-34743",
          quantity: 9,
          rate: 35,
          category_id: 8,
          name: "Dish (D)",
          createdAt: new Date(),
          updatedAt: new Date()
        },
        {
          id: 43,
          key: 43,
          sku: "Disco_light",
          quantity: 10,
          rate: 500,
          category_id: 14,
          name: "Disco Light",
          createdAt: new Date(),
          updatedAt: new Date()
        },
        {
          id: 44,
          key: 44,
          sku: "Dn_32787",
          quantity: 30,
          rate: 25,
          category_id: 14,
          name: "Dastarkhan",
          createdAt: new Date(),
          updatedAt: new Date()
        },
        {
          id: 45,
          key: 45,
          sku: "DP_75283",
          quantity: 200,
          rate: 10,
          category_id: 7,
          name: "Dinner Plate (Melamine)",
          createdAt: new Date(),
          updatedAt: new Date()
        },
        {
          id: 46,
          key: 46,
          sku: "Dr-3274",
          quantity: 30,
          rate: 80,
          category_id: 13,
          name: "Dari",
          createdAt: new Date(),
          updatedAt: new Date()
        },
        {
          id: 47,
          key: 47,
          sku: "DS-77666",
          quantity: 38,
          rate: 10,
          category_id: 8,
          name: "Dish Spoon",
          createdAt: new Date(),
          updatedAt: new Date()
        },
        {
          id: 48,
          key: 48,
          sku: "D_32354",
          quantity: 10,
          rate: 50,
          category_id: 14,
          name: "Dafli",
          createdAt: new Date(),
          updatedAt: new Date()
        },
        {
          id: 49,
          key: 49,
          sku: "D_3465",
          quantity: 7,
          rate: 150,
          category_id: 14,
          name: "Dhol",
          createdAt: new Date(),
          updatedAt: new Date()
        },
        {
          id: 50,
          key: 50,
          sku: "D_N 001",
          quantity: 1,
          rate: 8000,
          category_id: 14,
          name: "Dayra 60*60 Net square",
          createdAt: new Date(),
          updatedAt: new Date()
        },
        {
          id: 51,
          key: 51,
          sku: "D_N 002",
          quantity: 1,
          rate: 2000,
          category_id: 14,
          name: "Dayra 30*30 Net",
          createdAt: new Date(),
          updatedAt: new Date()
        },
        {
          id: 52,
          key: 52,
          sku: "D_N 003",
          quantity: 1,
          rate: 2500,
          category_id: 14,
          name: "Dayra 40*40",
          createdAt: new Date(),
          updatedAt: new Date()
        },
        {
          id: 53,
          key: 53,
          sku: "D_P",
          quantity: 10,
          rate: 150,
          category_id: 14,
          name: "Drawing Pins + Tissues",
          createdAt: new Date(),
          updatedAt: new Date()
        },
        {
          id: 54,
          key: 54,
          sku: "D_P_I",
          quantity: 10,
          rate: 150,
          category_id: 14,
          name: "Drawing Pins + Ispirt",
          createdAt: new Date(),
          updatedAt: new Date()
        },
        {
          id: 55,
          key: 55,
          sku: "D_P_P",
          quantity: 100,
          rate: 25,
          category_id: 7,
          name: "Dinner Plate ( Pyrix )",
          createdAt: new Date(),
          updatedAt: new Date()
        },
        {
          id: 56,
          key: 56,
          sku: "D_R",
          quantity: 10,
          rate: 100,
          category_id: 14,
          name: "Dari (N)",
          createdAt: new Date(),
          updatedAt: new Date()
        },
        {
          id: 57,
          key: 57,
          sku: "D_S_P",
          quantity: 100,
          rate: 25,
          category_id: 7,
          name: "Dessert Plate ( Pyrix )",
          createdAt: new Date(),
          updatedAt: new Date()
        },
        {
          id: 58,
          key: 58,
          sku: "D_TB_101",
          quantity: 12,
          rate: 100,
          category_id: 9,
          name: "Dining Table Border",
          createdAt: new Date(),
          updatedAt: new Date()
        },
        {
          id: 59,
          key: 59,
          sku: "D_TC_10",
          quantity: 12,
          rate: 200,
          category_id: 10,
          name: "Dining Table Cover",
          createdAt: new Date(),
          updatedAt: new Date()
        },
        {
          id: 60,
          key: 60,
          sku: "D_T_D",
          quantity: 3,
          rate: 100,
          category_id: 14,
          name: "Drum Type Duff",
          createdAt: new Date(),
          updatedAt: new Date()
        },
        {
          id: 61,
          key: 61,
          sku: "E-G",
          quantity: 2,
          rate: 500,
          category_id: 14,
          name: "Entry Gate",
          createdAt: new Date(),
          updatedAt: new Date()
        },
        {
          id: 62,
          key: 62,
          sku: "Fan",
          quantity: 10,
          rate: 300,
          category_id: 14,
          name: "Fan",
          createdAt: new Date(),
          updatedAt: new Date()
        },
        {
          id: 63,
          key: 63,
          sku: "FCr_11010",
          quantity: 15,
          rate: 100,
          category_id: 4,
          name: "Fancy Cover",
          createdAt: new Date(),
          updatedAt: new Date()
        },
        {
          id: 64,
          key: 64,
          sku: "FK_1001",
          quantity: 100,
          rate: 10,
          category_id: 14,
          name: "Fork",
          createdAt: new Date(),
          updatedAt: new Date()
        },
        {
          id: 65,
          key: 65,
          sku: "FN_326",
          quantity: 4,
          rate: 200,
          category_id: 14,
          name: "Fan",
          createdAt: new Date(),
          updatedAt: new Date()
        },
        {
          id: 66,
          key: 66,
          sku: "F_C_B",
          quantity: 80,
          rate: 7,
          category_id: 14,
          name: "Fruit Chaat Ball",
          createdAt: new Date(),
          updatedAt: new Date()
        },
        {
          id: 67,
          key: 67,
          sku: "F_D_C 041",
          quantity: 10,
          rate: 500,
          category_id: 14,
          name: "Flower Decoration Charges",
          createdAt: new Date(),
          updatedAt: new Date()
        },
        {
          id: 68,
          key: 68,
          sku: "F_J",
          quantity: 1,
          rate: 5500,
          category_id: 14,
          name: "Flower withJhoola",
          createdAt: new Date(),
          updatedAt: new Date()
        },
        {
          id: 69,
          key: 69,
          sku: "F_J_P",
          quantity: 1,
          rate: 4250,
          category_id: 14,
          name: "Flower jewelry, neck less and gende ke phool",
          createdAt: new Date(),
          updatedAt: new Date()
        },
        {
          id: 70,
          key: 70,
          sku: "F_P_K 001",
          quantity: 18,
          rate: 250,
          category_id: 5,
          name: "Frill Panal Kanaat",
          createdAt: new Date(),
          updatedAt: new Date()
        },
        {
          id: 71,
          key: 71,
          sku: "F_R_H 015",
          quantity: 6,
          rate: 300,
          category_id: 14,
          name: "Flip Round Hotpot",
          createdAt: new Date(),
          updatedAt: new Date()
        },
        {
          id: 72,
          key: 72,
          sku: "F_R_T 004",
          quantity: 4,
          rate: 1200,
          category_id: 2,
          name: "Frill Tent",
          createdAt: new Date(),
          updatedAt: new Date()
        },
        {
          id: 73,
          key: 73,
          sku: "F_T_100",
          quantity: 36,
          rate: 60,
          category_id: 14,
          name: "FLee Tissues",
          createdAt: new Date(),
          updatedAt: new Date()
        },
        {
          id: 74,
          key: 74,
          sku: "G-f-S",
          quantity: 1,
          rate: 2000,
          category_id: 14,
          name: "Gende flower of stairs",
          createdAt: new Date(),
          updatedAt: new Date()
        },
        {
          id: 75,
          key: 75,
          sku: "Gene",
          quantity: 1,
          rate: 1200,
          category_id: 14,
          name: "Generator",
          createdAt: new Date(),
          updatedAt: new Date()
        },
        {
          id: 76,
          key: 76,
          sku: "GL_2020",
          quantity: 100,
          rate: 0,
          category_id: 6,
          name: "Glass",
          createdAt: new Date(),
          updatedAt: new Date()
        },
        {
          id: 77,
          key: 77,
          sku: "gp 2",
          quantity: 2,
          rate: 20,
          category_id: 14,
          name: "Gulpaash",
          createdAt: new Date(),
          updatedAt: new Date()
        },
        {
          id: 78,
          key: 78,
          sku: "Gs-45277",
          quantity: 240,
          rate: 10,
          category_id: 6,
          name: "Glass",
          createdAt: new Date(),
          updatedAt: new Date()
        },
        {
          id: 79,
          key: 79,
          sku: "G_J",
          quantity: 3,
          rate: 35,
          category_id: 14,
          name: "glass jug",
          createdAt: new Date(),
          updatedAt: new Date()
        },
        {
          id: 80,
          key: 80,
          sku: "G_P",
          quantity: 5,
          rate: 100,
          category_id: 14,
          name: "Generator Petrol",
          createdAt: new Date(),
          updatedAt: new Date()
        },
        {
          id: 81,
          key: 81,
          sku: "H_P 0014",
          quantity: 23,
          rate: 150,
          category_id: 14,
          name: "HOT_POT",
          createdAt: new Date(),
          updatedAt: new Date()
        },
        {
          id: 82,
          key: 82,
          sku: "H_T",
          quantity: 50,
          rate: 70,
          category_id: 14,
          name: "Hanger Light Raju",
          createdAt: new Date(),
          updatedAt: new Date()
        },
        {
          id: 83,
          key: 83,
          sku: "Ice-B80",
          quantity: 80,
          rate: 5,
          category_id: 14,
          name: "Ice Bowl",
          createdAt: new Date(),
          updatedAt: new Date()
        },
        {
          id: 84,
          key: 84,
          sku: "I_C",
          quantity: 2,
          rate: 350,
          category_id: 14,
          name: "Ice",
          createdAt: new Date(),
          updatedAt: new Date()
        },
        {
          id: 85,
          key: 85,
          sku: "J-L-12",
          quantity: 100,
          rate: 70,
          category_id: 14,
          name: "jugnoo_light Raju",
          createdAt: new Date(),
          updatedAt: new Date()
        },
        {
          id: 86,
          key: 86,
          sku: "JH",
          quantity: 1,
          rate: 6500,
          category_id: 14,
          name: "Jhoola (With Flowers)",
          createdAt: new Date(),
          updatedAt: new Date()
        },
        {
          id: 87,
          key: 87,
          sku: "JJ-584",
          quantity: 29,
          rate: 25,
          category_id: 14,
          name: "Jug",
          createdAt: new Date(),
          updatedAt: new Date()
        },
        {
          id: 88,
          key: 88,
          sku: "J_L",
          quantity: 10,
          rate: 100,
          category_id: 14,
          name: "jugnoo_light",
          createdAt: new Date(),
          updatedAt: new Date()
        },
        {
          id: 89,
          key: 89,
          sku: "K_N",
          quantity: 2,
          rate: 500,
          category_id: 14,
          name: "Knoopy",
          createdAt: new Date(),
          updatedAt: new Date()
        },
        {
          id: 90,
          key: 90,
          sku: "K_N 005",
          quantity: 16,
          rate: 100,
          category_id: 5,
          name: "Kanaat",
          createdAt: new Date(),
          updatedAt: new Date()
        },
        {
          id: 91,
          key: 91,
          sku: "K_N 006",
          quantity: 16,
          rate: 100,
          category_id: 5,
          name: "Kanaat",
          createdAt: new Date(),
          updatedAt: new Date()
        },
        {
          id: 92,
          key: 92,
          sku: "K_N 007",
          quantity: 12,
          rate: 100,
          category_id: 5,
          name: "Kanaat",
          createdAt: new Date(),
          updatedAt: new Date()
        },
        {
          id: 93,
          key: 93,
          sku: "K_N 008",
          quantity: 11,
          rate: 100,
          category_id: 5,
          name: "Kanaat",
          createdAt: new Date(),
          updatedAt: new Date()
        },
        {
          id: 94,
          key: 94,
          sku: "K_N_F",
          quantity: 60,
          rate: 10,
          category_id: 14,
          name: "knife",
          createdAt: new Date(),
          updatedAt: new Date()
        },
        {
          id: 95,
          key: 95,
          sku: "k_N_O",
          quantity: 2,
          rate: 500,
          category_id: 14,
          name: "Kanoopy",
          createdAt: new Date(),
          updatedAt: new Date()
        },
        {
          id: 96,
          key: 96,
          sku: "K_T",
          quantity: 10,
          rate: 85,
          category_id: 14,
          name: "Kitchen Towel",
          createdAt: new Date(),
          updatedAt: new Date()
        },
        {
          id: 97,
          key: 97,
          sku: "L-B 2",
          quantity: 2,
          rate: 200,
          category_id: 14,
          name: "Labor Service",
          createdAt: new Date(),
          updatedAt: new Date()
        },
        {
          id: 98,
          key: 98,
          sku: "L-B 3",
          quantity: 2,
          rate: 300,
          category_id: 14,
          name: "Labor Service",
          createdAt: new Date(),
          updatedAt: new Date()
        },
        {
          id: 99,
          key: 99,
          sku: "L-B-1",
          quantity: 2,
          rate: 150,
          category_id: 14,
          name: "Labor Service",
          createdAt: new Date(),
          updatedAt: new Date()
        },
        {
          id: 100,
          key: 100,
          sku: "L-C !!",
          quantity: 1,
          rate: 400,
          category_id: 14,
          name: "Lifting charges",
          createdAt: new Date(),
          updatedAt: new Date()
        },
        {
          id: 101,
          key: 101,
          sku: "L-D-L",
          quantity: 4,
          rate: 500,
          category_id: 14,
          name: "LED_light",
          createdAt: new Date(),
          updatedAt: new Date()
        },
        {
          id: 102,
          key: 102,
          sku: "L-F",
          quantity: 1,
          rate: 3000,
          category_id: 14,
          name: "Lifting Charges",
          createdAt: new Date(),
          updatedAt: new Date()
        },
        {
          id: 103,
          key: 103,
          sku: "LB",
          quantity: 1,
          rate: 500,
          category_id: 8,
          name: "Dish Wash Service",
          createdAt: new Date(),
          updatedAt: new Date()
        },
        {
          id: 104,
          key: 104,
          sku: "Lc20",
          quantity: 1,
          rate: 700,
          category_id: 14,
          name: "Lifting charges",
          createdAt: new Date(),
          updatedAt: new Date()
        },
        {
          id: 105,
          key: 105,
          sku: "LchC_10012",
          quantity: 0,
          rate: 0,
          category_id: 14,
          name: "LchC_10012",
          createdAt: new Date(),
          updatedAt: new Date()
        },
        {
          id: 106,
          key: 106,
          sku: "Long Back Chair Cover",
          quantity: 0,
          rate: 10,
          category_id: 4,
          name: "Long Back Chair Cover",
          createdAt: new Date(),
          updatedAt: new Date()
        },
        {
          id: 107,
          key: 107,
          sku: "LCh_10011",
          quantity: 100,
          rate: 30,
          category_id: 3,
          name: "Long Back Chair",
          createdAt: new Date(),
          updatedAt: new Date()
        },
        {
          id: 108,
          key: 108,
          sku: "LC_52267",
          quantity: 500,
          rate: 2500,
          category_id: 14,
          name: "Lifting Charges",
          createdAt: new Date(),
          updatedAt: new Date()
        },
        {
          id: 109,
          key: 109,
          sku: "Lights",
          quantity: 50,
          rate: 100,
          category_id: 14,
          name: "Pak Hanger_light",
          createdAt: new Date(),
          updatedAt: new Date()
        },
        {
          id: 110,
          key: 110,
          sku: "LMP_101",
          quantity: 5,
          rate: 200,
          category_id: 14,
          name: "Lamp",
          createdAt: new Date(),
          updatedAt: new Date()
        },
        {
          id: 111,
          key: 111,
          sku: "LS02",
          quantity: 1,
          rate: 400,
          category_id: 14,
          name: "Labor Service",
          createdAt: new Date(),
          updatedAt: new Date()
        },
        {
          id: 112,
          key: 112,
          sku: "LS_1010",
          quantity: 12,
          rate: 600,
          category_id: 14,
          name: "Labor Service",
          createdAt: new Date(),
          updatedAt: new Date()
        },
        {
          id: 113,
          key: 113,
          sku: "L_A_chrg",
          quantity: 10,
          rate: 500,
          category_id: 14,
          name: "Lifting Charges",
          createdAt: new Date(),
          updatedAt: new Date()
        },
        {
          id: 114,
          key: 114,
          sku: "L_C",
          quantity: 1,
          rate: 600,
          category_id: 14,
          name: "Lifting charges",
          createdAt: new Date(),
          updatedAt: new Date()
        },
        {
          id: 115,
          key: 115,
          sku: "L_F_T",
          quantity: 1,
          rate: 100,
          category_id: 14,
          name: "Lifting charges",
          createdAt: new Date(),
          updatedAt: new Date()
        },
        {
          id: 116,
          key: 116,
          sku: "L_N",
          quantity: 4,
          rate: 500,
          category_id: 14,
          name: "Labor Night",
          createdAt: new Date(),
          updatedAt: new Date()
        },
        {
          id: 117,
          key: 117,
          sku: "L_P",
          quantity: 1,
          rate: 600,
          category_id: 14,
          name: "L P G Gas Cylinder",
          createdAt: new Date(),
          updatedAt: new Date()
        },
        {
          id: 118,
          key: 118,
          sku: "L_S",
          quantity: 6,
          rate: 6000,
          category_id: 14,
          name: "LOUNGES & SOFAS 10 Seater",
          createdAt: new Date(),
          updatedAt: new Date()
        },
        {
          id: 119,
          key: 119,
          sku: "Min_bottle",
          quantity: 100,
          rate: 50,
          category_id: 14,
          name: "Mineral water 1.5litr",
          createdAt: new Date(),
          updatedAt: new Date()
        },
        {
          id: 120,
          key: 120,
          sku: "M_642",
          quantity: 2,
          rate: 100,
          category_id: 14,
          name: "Mic",
          createdAt: new Date(),
          updatedAt: new Date()
        },
        {
          id: 121,
          key: 121,
          sku: "M_I_C",
          quantity: 10,
          rate: 160,
          category_id: 14,
          name: "Missing item charges",
          createdAt: new Date(),
          updatedAt: new Date()
        },
        {
          id: 122,
          key: 122,
          sku: "M_S",
          quantity: 1,
          rate: 0,
          category_id: 14,
          name: "Milaad screen",
          createdAt: new Date(),
          updatedAt: new Date()
        },
        {
          id: 123,
          key: 123,
          sku: "M_S_T",
          quantity: 2,
          rate: 100,
          category_id: 14,
          name: "Mic stand",
          createdAt: new Date(),
          updatedAt: new Date()
        },
        {
          id: 124,
          key: 124,
          sku: "Nap",
          quantity: 100,
          rate: 20,
          category_id: 14,
          name: "Napkin",
          createdAt: new Date(),
          updatedAt: new Date()
        },
        {
          id: 125,
          key: 125,
          sku: "N_C_N",
          quantity: 40,
          rate: 100,
          category_id: 14,
          name: "Net nNappron",
          createdAt: new Date(),
          updatedAt: new Date()
        },
        {
          id: 126,
          key: 126,
          sku: "N_C_N )023",
          quantity: 40,
          rate: 200,
          category_id: 14,
          name: "Net Curtain",
          createdAt: new Date(),
          updatedAt: new Date()
        },
        {
          id: 127,
          key: 127,
          sku: "N_P_R 007",
          quantity: 40,
          rate: 70,
          category_id: 14,
          name: "Nappron",
          createdAt: new Date(),
          updatedAt: new Date()
        },
        {
          id: 128,
          key: 128,
          sku: "P-G",
          quantity: 0,
          rate: 200,
          category_id: 14,
          name: "Petrol Generator",
          createdAt: new Date(),
          updatedAt: new Date()
        },
        {
          id: 129,
          key: 129,
          sku: "PLD-75283",
          quantity: 200,
          rate: 12,
          category_id: 7,
          name: "Dinner Plate (Melamine)",
          createdAt: new Date(),
          updatedAt: new Date()
        },
        {
          id: 130,
          key: 130,
          sku: "Pld-75284",
          quantity: 200,
          rate: 12,
          category_id: 7,
          name: "Dessert Plate (Melamine)",
          createdAt: new Date(),
          updatedAt: new Date()
        },
        {
          id: 131,
          key: 131,
          sku: "PlD_33822",
          quantity: 120,
          rate: 14,
          category_id: 7,
          name: "Dessert Plate (D)",
          createdAt: new Date(),
          updatedAt: new Date()
        },
        {
          id: 132,
          key: 132,
          sku: "PlD_38224",
          quantity: 120,
          rate: 14,
          category_id: 7,
          name: "Dinner Plate (D)",
          createdAt: new Date(),
          updatedAt: new Date()
        },
        {
          id: 133,
          key: 133,
          sku: "PLM-75284",
          quantity: 150,
          rate: 7,
          category_id: 7,
          name: "Dinner Plate (M)",
          createdAt: new Date(),
          updatedAt: new Date()
        },
        {
          id: 134,
          key: 134,
          sku: "PLMs-75284",
          quantity: 150,
          rate: 7,
          category_id: 7,
          name: "Dessert Plate (Melamine)",
          createdAt: new Date(),
          updatedAt: new Date()
        },
        {
          id: 135,
          key: 135,
          sku: "P_75283",
          quantity: 200,
          rate: 10,
          category_id: 7,
          name: "Dessert Plate (Melamine)",
          createdAt: new Date(),
          updatedAt: new Date()
        },
        {
          id: 136,
          key: 136,
          sku: "P_F 040",
          quantity: 248,
          rate: 12,
          category_id: 14,
          name: "Paper Flowers string",
          createdAt: new Date(),
          updatedAt: new Date()
        },
        {
          id: 137,
          key: 137,
          sku: "P_K 004",
          quantity: 20,
          rate: 150,
          category_id: 5,
          name: "Panal Kanaat",
          createdAt: new Date(),
          updatedAt: new Date()
        },
        {
          id: 138,
          key: 138,
          sku: "P_K_L",
          quantity: 42,
          rate: 70,
          category_id: 14,
          name: "PAK Saver_light",
          createdAt: new Date(),
          updatedAt: new Date()
        },
        {
          id: 139,
          key: 139,
          sku: "p_L",
          quantity: 4,
          rate: 400,
          category_id: 14,
          name: "Panal 4x8",
          createdAt: new Date(),
          updatedAt: new Date()
        },
        {
          id: 140,
          key: 140,
          sku: "P_P",
          quantity: 10,
          rate: 60,
          category_id: 14,
          name: "Party Pack",
          createdAt: new Date(),
          updatedAt: new Date()
        },
        {
          id: 141,
          key: 141,
          sku: "P_S",
          quantity: 2,
          rate: 700,
          category_id: 14,
          name: "Panaflex sheet 12 * 30",
          createdAt: new Date(),
          updatedAt: new Date()
        },
        {
          id: 142,
          key: 142,
          sku: "R B 01",
          quantity: 60,
          rate: 5,
          category_id: 14,
          name: "Ribbon",
          createdAt: new Date(),
          updatedAt: new Date()
        },
        {
          id: 143,
          key: 143,
          sku: "R-F-S",
          quantity: 1,
          rate: 8000,
          category_id: 14,
          name: "Regular flowers Stage",
          createdAt: new Date(),
          updatedAt: new Date()
        },
        {
          id: 144,
          key: 144,
          sku: "ReSp_7377",
          quantity: 38,
          rate: 10,
          category_id: 14,
          name: "Rice Spoon",
          createdAt: new Date(),
          updatedAt: new Date()
        },
        {
          id: 145,
          key: 145,
          sku: "RN",
          quantity: 6,
          rate: 200,
          category_id: 14,
          name: "Runner",
          createdAt: new Date(),
          updatedAt: new Date()
        },
        {
          id: 146,
          key: 146,
          sku: "R_C_R 004",
          quantity: 4,
          rate: 400,
          category_id: 14,
          name: "Carpet Runner",
          createdAt: new Date(),
          updatedAt: new Date()
        },
        {
          id: 147,
          key: 147,
          sku: "R_F",
          quantity: 5,
          rate: 5000,
          category_id: 14,
          name: "Real flower stand",
          createdAt: new Date(),
          updatedAt: new Date()
        },
        {
          id: 148,
          key: 148,
          sku: "R_L_C 001",
          quantity: 10,
          rate: 200,
          category_id: 14,
          name: "Red Lining Carpet",
          createdAt: new Date(),
          updatedAt: new Date()
        },
        {
          id: 149,
          key: 149,
          sku: "R_S",
          quantity: 5,
          rate: 200,
          category_id: 14,
          name: "Regular screen",
          createdAt: new Date(),
          updatedAt: new Date()
        },
        {
          id: 150,
          key: 150,
          sku: "R_T 001",
          quantity: 10,
          rate: 100,
          category_id: 9,
          name: "Round Table",
          createdAt: new Date(),
          updatedAt: new Date()
        },
        {
          id: 151,
          key: 151,
          sku: "R_T_C 006",
          quantity: 50,
          rate: 100,
          category_id: 10,
          name: "Round Table Cover",
          createdAt: new Date(),
          updatedAt: new Date()
        },
        {
          id: 152,
          key: 152,
          sku: "R_T_G 003",
          quantity: 10,
          rate: 400,
          category_id: 9,
          name: "Round Table (Glass)",
          createdAt: new Date(),
          updatedAt: new Date()
        },
        {
          id: 153,
          key: 153,
          sku: "R_T_I",
          quantity: 10,
          rate: 200,
          category_id: 9,
          name: "Round Table Iron",
          createdAt: new Date(),
          updatedAt: new Date()
        },
        {
          id: 154,
          key: 154,
          sku: "s-k",
          quantity: 2,
          rate: 0,
          category_id: 14,
          name: "Speaker",
          createdAt: new Date(),
          updatedAt: new Date()
        },
        {
          id: 155,
          key: 155,
          sku: "S-L 12",
          quantity: 100,
          rate: 70,
          category_id: 14,
          name: "Saver_light Raju",
          createdAt: new Date(),
          updatedAt: new Date()
        },
        {
          id: 156,
          key: 156,
          sku: "S-T",
          quantity: 1,
          rate: 15000,
          category_id: 14,
          name: "flowers Stage",
          createdAt: new Date(),
          updatedAt: new Date()
        },
        {
          id: 157,
          key: 157,
          sku: "S-T 02A",
          quantity: 102,
          rate: 10,
          category_id: 14,
          name: "Tea Spoon A",
          createdAt: new Date(),
          updatedAt: new Date()
        },
        {
          id: 158,
          key: 158,
          sku: "S-W",
          quantity: 2,
          rate: 1000,
          category_id: 14,
          name: "Waiter Only Service",
          createdAt: new Date(),
          updatedAt: new Date()
        },
        {
          id: 159,
          key: 159,
          sku: "ScSp_7277",
          quantity: 44,
          rate: 10,
          category_id: 14,
          name: "Service Spoon",
          createdAt: new Date(),
          updatedAt: new Date()
        },
        {
          id: 160,
          key: 160,
          sku: "SP 002",
          quantity: 2,
          rate: 2000,
          category_id: 14,
          name: "Sound SP 2",
          createdAt: new Date(),
          updatedAt: new Date()
        },
        {
          id: 161,
          key: 161,
          sku: "SP_4",
          quantity: 0,
          rate: 3500,
          category_id: 14,
          name: "Sound System SP-4",
          createdAt: new Date(),
          updatedAt: new Date()
        },
        {
          id: 162,
          key: 162,
          sku: "SS_10",
          quantity: 1,
          rate: 800,
          category_id: 14,
          name: "Sound System",
          createdAt: new Date(),
          updatedAt: new Date()
        },
        {
          id: 163,
          key: 163,
          sku: "SS_76863",
          quantity: 3,
          rate: 1000,
          category_id: 14,
          name: "Sound System SP-1",
          createdAt: new Date(),
          updatedAt: new Date()
        },
        {
          id: 164,
          key: 164,
          sku: "SS_stair",
          quantity: 5,
          rate: 150,
          category_id: 14,
          name: "Stage Stairs",
          createdAt: new Date(),
          updatedAt: new Date()
        },
        {
          id: 165,
          key: 165,
          sku: "STH_84225",
          quantity: 47,
          rate: 20,
          category_id: 14,
          name: "Service Thaal",
          createdAt: new Date(),
          updatedAt: new Date()
        },
        {
          id: 166,
          key: 166,
          sku: "ST_84225",
          quantity: 25,
          rate: 25,
          category_id: 14,
          name: "Service Thaal (M)",
          createdAt: new Date(),
          updatedAt: new Date()
        },
        {
          id: 167,
          key: 167,
          sku: "S_B_80",
          quantity: 80,
          rate: 7,
          category_id: 14,
          name: "Sweet Bowl",
          createdAt: new Date(),
          updatedAt: new Date()
        },
        {
          id: 168,
          key: 168,
          sku: "S_chr12",
          quantity: 2,
          rate: 200,
          category_id: 3,
          name: "Sadarti Chair",
          createdAt: new Date(),
          updatedAt: new Date()
        },
        {
          id: 169,
          key: 169,
          sku: "S_light",
          quantity: 10,
          rate: 200,
          category_id: 14,
          name: "Search light",
          createdAt: new Date(),
          updatedAt: new Date()
        },
        {
          id: 170,
          key: 170,
          sku: "S_P",
          quantity: 1,
          rate: 4500,
          category_id: 14,
          name: "Sound System SP-2",
          createdAt: new Date(),
          updatedAt: new Date()
        },
        {
          id: 171,
          key: 171,
          sku: "S_Q_T 004",
          quantity: 21,
          rate: 100,
          category_id: 9,
          name: "Rectangle Table",
          createdAt: new Date(),
          updatedAt: new Date()
        },
        {
          id: 172,
          key: 172,
          sku: "S_Q_T 005",
          quantity: 6,
          rate: 200,
          category_id: 9,
          name: "Square Table (4x4)",
          createdAt: new Date(),
          updatedAt: new Date()
        },
        {
          id: 173,
          key: 173,
          sku: "S_Q_T_C 001",
          quantity: 50,
          rate: 50,
          category_id: 10,
          name: "Square Table Cover",
          createdAt: new Date(),
          updatedAt: new Date()
        },
        {
          id: 174,
          key: 174,
          sku: "S_Q_T_C 002",
          quantity: 30,
          rate: 100,
          category_id: 10,
          name: "Table Cover (4x4)",
          createdAt: new Date(),
          updatedAt: new Date()
        },
        {
          id: 175,
          key: 175,
          sku: "S_Q_T_C 003",
          quantity: 50,
          rate: 70,
          category_id: 10,
          name: "Table Cover (4x4) Dabbi patti",
          createdAt: new Date(),
          updatedAt: new Date()
        },
        {
          id: 176,
          key: 176,
          sku: "S_S",
          quantity: 9,
          rate: 1200,
          category_id: 14,
          name: "SOFA SET",
          createdAt: new Date(),
          updatedAt: new Date()
        },
        {
          id: 177,
          key: 177,
          sku: "S_S_20202",
          quantity: 40,
          rate: 15,
          category_id: 14,
          name: "Service Spoon",
          createdAt: new Date(),
          updatedAt: new Date()
        },
        {
          id: 178,
          key: 178,
          sku: "S_T",
          quantity: 6,
          rate: 800,
          category_id: 14,
          name: "Sitting sethi 6 set",
          createdAt: new Date(),
          updatedAt: new Date()
        },
        {
          id: 179,
          key: 179,
          sku: "T-B Q A",
          quantity: 102,
          rate: 10,
          category_id: 9,
          name: "Table Spoon A",
          createdAt: new Date(),
          updatedAt: new Date()
        },
        {
          id: 180,
          key: 180,
          sku: "t-i s",
          quantity: 300,
          rate: 80,
          category_id: 14,
          name: "Tissue",
          createdAt: new Date(),
          updatedAt: new Date()
        },
        {
          id: 181,
          key: 181,
          sku: "T-R 0112",
          quantity: 2,
          rate: 700,
          category_id: 11,
          name: "Transportation",
          createdAt: new Date(),
          updatedAt: new Date()
        },
        {
          id: 182,
          key: 182,
          sku: "T-S",
          quantity: 102,
          rate: 10,
          category_id: 9,
          name: "Table Spoon B",
          createdAt: new Date(),
          updatedAt: new Date()
        },
        {
          id: 183,
          key: 183,
          sku: "T-S QB",
          quantity: 102,
          rate: 5,
          category_id: 9,
          name: "table Spoon B",
          createdAt: new Date(),
          updatedAt: new Date()
        },
        {
          id: 184,
          key: 184,
          sku: "TbSp_8277",
          quantity: 230,
          rate: 3,
          category_id: 9,
          name: "Table Spoon",
          createdAt: new Date(),
          updatedAt: new Date()
        },
        {
          id: 185,
          key: 185,
          sku: "TB_882",
          quantity: 5,
          rate: 100,
          category_id: 14,
          name: "Tub",
          createdAt: new Date(),
          updatedAt: new Date()
        },
        {
          id: 186,
          key: 186,
          sku: "TB_CV_101",
          quantity: 20,
          rate: 100,
          category_id: 10,
          name: "Table cover",
          createdAt: new Date(),
          updatedAt: new Date()
        },
        {
          id: 187,
          key: 187,
          sku: "TeSp_8277",
          quantity: 240,
          rate: 3,
          category_id: 14,
          name: "Tea Spoon",
          createdAt: new Date(),
          updatedAt: new Date()
        },
        {
          id: 188,
          key: 188,
          sku: "Tkht-102",
          quantity: 1,
          rate: 2000,
          category_id: 14,
          name: "Last Balance bill adjustment",
          createdAt: new Date(),
          updatedAt: new Date()
        },
        {
          id: 189,
          key: 189,
          sku: "Tr",
          quantity: 2,
          rate: 600,
          category_id: 11,
          name: "Transportation",
          createdAt: new Date(),
          updatedAt: new Date()
        },
        {
          id: 190,
          key: 190,
          sku: "TR250",
          quantity: 2,
          rate: 250,
          category_id: 11,
          name: "Transportation",
          createdAt: new Date(),
          updatedAt: new Date()
        },
        {
          id: 191,
          key: 191,
          sku: "TRP",
          quantity: 2,
          rate: 400,
          category_id: 11,
          name: "Transportation",
          createdAt: new Date(),
          updatedAt: new Date()
        },
        {
          id: 192,
          key: 192,
          sku: "TS 02A",
          quantity: 100,
          rate: 15,
          category_id: 14,
          name: "Teble Spoon A",
          createdAt: new Date(),
          updatedAt: new Date()
        },
        {
          id: 193,
          key: 193,
          sku: "T_100",
          quantity: 25,
          rate: 300,
          category_id: 11,
          name: "Transportation",
          createdAt: new Date(),
          updatedAt: new Date()
        },
        {
          id: 194,
          key: 194,
          sku: "T_1010",
          quantity: 10,
          rate: 150,
          category_id: 11,
          name: "Transportation",
          createdAt: new Date(),
          updatedAt: new Date()
        },
        {
          id: 195,
          key: 195,
          sku: "T_120",
          quantity: 150,
          rate: 150,
          category_id: 11,
          name: "Transportation",
          createdAt: new Date(),
          updatedAt: new Date()
        },
        {
          id: 196,
          key: 196,
          sku: "T_1234",
          quantity: 200,
          rate: 200,
          category_id: 11,
          name: "Transportation",
          createdAt: new Date(),
          updatedAt: new Date()
        },
        {
          id: 197,
          key: 197,
          sku: "T_B 010",
          quantity: 70,
          rate: 100,
          category_id: 9,
          name: "Table Border",
          createdAt: new Date(),
          updatedAt: new Date()
        },
        {
          id: 198,
          key: 198,
          sku: "T_B_B",
          quantity: 1,
          rate: 200,
          category_id: 14,
          name: "BIG TUB",
          createdAt: new Date(),
          updatedAt: new Date()
        },
        {
          id: 199,
          key: 199,
          sku: "T_C_K_M",
          quantity: 20,
          rate: 100,
          category_id: 9,
          name: "Table Cloth for Kebab Maker",
          createdAt: new Date(),
          updatedAt: new Date()
        },
        {
          id: 200,
          key: 200,
          sku: "T_F_K 002",
          quantity: 20,
          rate: 150,
          category_id: 5,
          name: "Top Frill Kanaat",
          createdAt: new Date(),
          updatedAt: new Date()
        },
        {
          id: 201,
          key: 201,
          sku: "T_F_K 003",
          quantity: 20,
          rate: 150,
          category_id: 5,
          name: "Top Frill Kanaat",
          createdAt: new Date(),
          updatedAt: new Date()
        },
        {
          id: 202,
          key: 202,
          sku: "T_I",
          quantity: 2,
          rate: 150,
          category_id: 14,
          name: "Tissues + Ispirt",
          createdAt: new Date(),
          updatedAt: new Date()
        },
        {
          id: 203,
          key: 203,
          sku: "T_K 001",
          quantity: 15,
          rate: 200,
          category_id: 14,
          name: "Takht",
          createdAt: new Date(),
          updatedAt: new Date()
        },
        {
          id: 204,
          key: 204,
          sku: "T_K 002",
          quantity: 15,
          rate: 150,
          category_id: 14,
          name: "Takht",
          createdAt: new Date(),
          updatedAt: new Date()
        },
        {
          id: 205,
          key: 205,
          sku: "T_L",
          quantity: 4,
          rate: 150,
          category_id: 9,
          name: "table of Lamp",
          createdAt: new Date(),
          updatedAt: new Date()
        },
        {
          id: 206,
          key: 206,
          sku: "T_N 005",
          quantity: 4,
          rate: 700,
          category_id: 2,
          name: "Tent",
          createdAt: new Date(),
          updatedAt: new Date()
        },
        {
          id: 207,
          key: 207,
          sku: "T_N 006",
          quantity: 6,
          rate: 700,
          category_id: 2,
          name: "Tent",
          createdAt: new Date(),
          updatedAt: new Date()
        },
        {
          id: 208,
          key: 208,
          sku: "T_N 007",
          quantity: 2,
          rate: 500,
          category_id: 2,
          name: "Tent",
          createdAt: new Date(),
          updatedAt: new Date()
        },
        {
          id: 209,
          key: 209,
          sku: "T_N 008",
          quantity: 4,
          rate: 700,
          category_id: 2,
          name: "Tent",
          createdAt: new Date(),
          updatedAt: new Date()
        },
        {
          id: 210,
          key: 210,
          sku: "T_N 009",
          quantity: 2,
          rate: 500,
          category_id: 2,
          name: "Tent",
          createdAt: new Date(),
          updatedAt: new Date()
        },
        {
          id: 211,
          key: 211,
          sku: "T_N 010",
          quantity: 5,
          rate: 700,
          category_id: 2,
          name: "Tent",
          createdAt: new Date(),
          updatedAt: new Date()
        },
        {
          id: 212,
          key: 212,
          sku: "T_N 011",
          quantity: 1,
          rate: 700,
          category_id: 2,
          name: "Tent",
          createdAt: new Date(),
          updatedAt: new Date()
        },
        {
          id: 213,
          key: 213,
          sku: "T_R",
          quantity: 1,
          rate: 100,
          category_id: 11,
          name: "Transportation",
          createdAt: new Date(),
          updatedAt: new Date()
        },
        {
          id: 214,
          key: 214,
          sku: "T_R 99",
          quantity: 4,
          rate: 400,
          category_id: 11,
          name: "Transportation",
          createdAt: new Date(),
          updatedAt: new Date()
        },
        {
          id: 215,
          key: 215,
          sku: "T_S",
          quantity: 102,
          rate: 5,
          category_id: 14,
          name: "Tea Spoon B",
          createdAt: new Date(),
          updatedAt: new Date()
        },
        {
          id: 216,
          key: 216,
          sku: "Vs",
          quantity: 12,
          rate: 100,
          category_id: 14,
          name: "Vase",
          createdAt: new Date(),
          updatedAt: new Date()
        },
        {
          id: 217,
          key: 217,
          sku: "VS_1",
          quantity: 20,
          rate: 150,
          category_id: 14,
          name: "Vase",
          createdAt: new Date(),
          updatedAt: new Date()
        },
        {
          id: 218,
          key: 218,
          sku: "w-l-c",
          quantity: 1,
          rate: 1500,
          category_id: 14,
          name: "welcome Gate",
          createdAt: new Date(),
          updatedAt: new Date()
        },
        {
          id: 219,
          key: 219,
          sku: "Waiter_shop",
          quantity: 3,
          rate: 600,
          category_id: 14,
          name: "Waiter",
          createdAt: new Date(),
          updatedAt: new Date()
        },
        {
          id: 220,
          key: 220,
          sku: "WB_22746",
          quantity: 2,
          rate: 250,
          category_id: 14,
          name: "Wash Basin",
          createdAt: new Date(),
          updatedAt: new Date()
        },
        {
          id: 221,
          key: 221,
          sku: "W_C_C",
          quantity: 100,
          rate: 100,
          category_id: 3,
          name: "White Chaivari Chair",
          createdAt: new Date(),
          updatedAt: new Date()
        }
      ],
      {}
    );
  },

  down: (queryInterface, Sequelize) => {
    /*
      Add reverting commands here.
      Return a promise to correctly handle asynchronicity.

      Example:
      return queryInterface.bulkDelete('People', null, {});
    */
  }
};
